version: '3.7'
services:
  opensearch:
    image: opensearchproject/opensearch:1.2.4
    environment:
      discovery.type: single-node
      plugins.security.disabled: "true" # disable https and logins
      compatibility.override_main_response_version: "true"
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  # console at http://localhost:5601/app/dev_tools#/console
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
# podman run -dt -p 9200:9200/tcp -p 9600:9600/tcp -e discovery.type=single-node -e plugins.security.disabled=true -e compatibility.override_main_response_version=true docker.io/opensearchproject/opensearch:1.2.4
# podman run -p 5601:5601/tcp -e OPENSEARCH_HOSTS='["http://opensearch:9200"]' -e DISABLE_SECURITY_DASHBOARDS_PLUGIN=true docker.io/opensearchproject/opensearch-dashboards:1.2.0

# podman play kube opensearch.yml --replace && podman play kube opensearch-dashboard.yml --replace